// ==========================================
// controllers/braintree.js - Payment Processing Logic
// ==========================================
// This controller integrates the Braintree Node.js SDK to handle payment transactions.

const braintree = require('braintree');
require('dotenv').config();

// ==========================================
// Initialize Braintree Gateway
// ==========================================
// Configures the Braintree connection using credentials stored in .env
const gateway = new braintree.BraintreeGateway({
  environment: braintree.Environment.Sandbox, // Using sandbox for testing, would be Production in real app
  merchantId: process.env.BRAINTREE_MERCHANT_ID,
  publicKey: process.env.BRAINTREE_PUBLIC_KEY,
  privateKey: process.env.BRAINTREE_PRIVATE_KEY,
});

// ==========================================
// Generate Client Token
// ==========================================
/**
 * @desc    Generates a unique client token that the frontend Drop-in UI needs
 *          to securely collect payment information from the user.
 */
exports.generateToken = (req, res) => {
  gateway.clientToken.generate({}, function (err, response) {
    if (err) {
      res.status(500).send(err);
    } else {
      // Send the token back to the frontend
      res.send(response);
    }
  });
};

// ==========================================
// Process Payment Transaction
// ==========================================
/**
 * @desc    Takes the payment method nonce (a secure, one-time-use reference to payment details)
 *          generated by the frontend, and the amount to be charged, then submits it to Braintree.
 */
exports.processPayment = (req, res) => {
  // Extract nonce and amount sent by the React frontend
  let nonceFromTheClient = req.body.paymentMethodNonce;
  let amountFromTheClient = req.body.amount;
  
  // Create a transaction via Braintree gateway
  let newTransaction = gateway.transaction.sale(
    {
      amount: amountFromTheClient,
      paymentMethodNonce: nonceFromTheClient,
      options: {
        submitForSettlement: true, // Immediately submit the transaction for settlement
      },
    },
    (error, result) => {
      if (error) {
        // If an error occurs during processing, return it to the client
        res.status(500).json(error);
      } else {
        // If successful, return the transaction result (contains transaction ID)
        res.json(result);
      }
    }
  );
};
